# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e43ba3edf98c7c9a322d8bd8d1704db0844c459c5192b2529db169bd5577976fe48433fa249f3db78456f3a902a0eb1220ccb7949e4624a639b2c0192eecddcf

test:
  secret_key_base: 372de133652b04937cf7342424c1385f3fd4fd36b96deecc5aba1a8bbffdcb0c21beca9c0d625f43d2879a12c80927617dbb891b25acd1a67be052c7c870b48d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
